// One-shot, idempotent, resumable bootstrap of GoHealthMe's ENSv2 namespace on
// Ethereum Sepolia (the 2026-09-15 deployment).
//
// Run from app/:   npm run ens:bootstrap            (does the work)
//                  npm run ens:bootstrap -- --plan  (reads only, prints what is left)
//
// What it builds, each step skipped when the chain already shows it done:
//   1. GoHealthMe's own UserRegistry proxy and PermissionedResolver proxy,
//      deployed through the VerifiableFactory, the owner key holding root roles.
//   2. gohealthme.eth registered on the ETHRegistrar (commit, wait, register),
//      paid in the deployment's MockUSDC, pointing at those two proxies. This is
//      the registry hierarchy: eth -> gohealthme -> our own registry.
//   3. spotter.gohealthme.eth registered TO the agent's Sepolia key with an
//      empty role bitmap: the agent owns its name and can do nothing with it.
//   4. spotter's address records: addr(60) = the agent's Sepolia key,
//      addr(84532) = the Base Sepolia settler read live from HealthPoolsV3.
//   5. Enhanced Access Control on the Permissioned Resolver: the agent is
//      granted ROLE_SET_TEXT on exactly the four receipt keys, nothing else.
//   6. A little Sepolia ETH for the agent so it can pay for receipt writes.
//
// Keys: the owner is ENS_OWNER_PRIVATE_KEY, else the deployer PRIVATE_KEY from
// contracts/.env. The agent is ENS_AGENT_PRIVATE_KEY; when absent a fresh key
// is generated and written to app/.env.local (gitignored, never printed).
// Every transaction is appended to DEPLOYMENTS.md under the Tokyo heading.
// The script refuses to take the owner below OWNER_FLOOR_ETH and prints the
// shortfall instead.

import { existsSync, mkdirSync, readFileSync, writeFileSync, appendFileSync } from "fs";
import path from "path";
import {
  createPublicClient,
  formatEther,
  http,
  keccak256,
  parseAbi,
  parseEther,
  parseEventLogs,
  stringToBytes,
  toHex,
  encodeFunctionData,
  type Account,
  type Address,
  type Hex,
  type TransactionReceipt,
} from "viem";
import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";
import { baseSepolia } from "viem/chains";
import {
  AGENT_LABEL,
  AGENT_NAME_ROLES,
  ALL_ROLES,
  BASE_SEPOLIA_COIN_TYPE,
  ETH_COIN_TYPE,
  RECEIPT_KEY_LIST,
  RESOLVER_ROLE_SET_TEXT,
  NO_EXPIRY,
  agentName,
  firstLabel,
  setAddressCalldata,
  textResource,
  textSetterGrant,
  sepoliaTxUrl,
} from "@/lib/ens/names";
import {
  ENS_SEPOLIA,
  ENS_SEPOLIA_ADDRESSES,
  ETH_REGISTRAR_ABI,
  MOCK_USDC_ABI,
  PERMISSIONED_RESOLVER_ABI,
  REGISTRY_ABI,
  VERIFIABLE_FACTORY_ABI,
} from "@/lib/server/ens/deployments";
import { ensPublicClient, ensWalletClient } from "@/lib/server/ens/client";

const APP_DIR = process.cwd();
const REPO_DIR = path.resolve(APP_DIR, "..");
const STATE_FILE = path.join(APP_DIR, ".data", "ens-bootstrap-state.json");
const DEPLOYMENTS = path.join(REPO_DIR, "DEPLOYMENTS.md");
const ENV_LOCAL = path.join(APP_DIR, ".env.local");
const TOKYO_HEADING = "## Tokyo 2026 (ENSv2 Sepolia)";

const OWNER_FLOOR_ETH = parseEther("0.005");
const AGENT_TOPUP_ETH = parseEther("0.003");
const AGENT_MIN_ETH = parseEther("0.001");
const REGISTRATION_SECONDS = 365n * 24n * 60n * 60n;
const ZERO: Address = "0x0000000000000000000000000000000000000000";
const PLAN_ONLY = process.argv.includes("--plan");

interface State {
  parent: string;
  registryProxy?: Address;
  resolverProxy?: Address;
  secret?: Hex;
  committedAt?: number;
  txs: { step: string; hash: Hex; gasEth: string }[];
}

function loadState(parent: string): State {
  try {
    const s = JSON.parse(readFileSync(STATE_FILE, "utf8")) as State;
    if (s.parent === parent) return s;
  } catch {
    // fresh
  }
  return { parent, txs: [] };
}

function saveState(state: State): void {
  mkdirSync(path.dirname(STATE_FILE), { recursive: true });
  writeFileSync(STATE_FILE, JSON.stringify(state, null, 2));
}

function envKey(names: string[]): Hex | null {
  for (const n of names) {
    const v = process.env[n]?.trim();
    if (v) return (v.startsWith("0x") ? v : `0x${v}`) as Hex;
  }
  return null;
}

function ensureAgentKey(): Account {
  const existing = envKey(["ENS_AGENT_PRIVATE_KEY"]);
  if (existing !== null) return privateKeyToAccount(existing);
  const key = generatePrivateKey();
  if (!PLAN_ONLY) {
    appendFileSync(
      ENV_LOCAL,
      `\n# SPOTTER's ENSv2 Sepolia signer (receipt writer), generated by scripts/ens-bootstrap.ts\nENS_AGENT_PRIVATE_KEY=${key}\n`,
    );
    console.log(`  generated a new agent key and wrote ENS_AGENT_PRIVATE_KEY to app/.env.local`);
  }
  return privateKeyToAccount(key);
}

function recordDeployment(line: string): void {
  let text = existsSync(DEPLOYMENTS) ? readFileSync(DEPLOYMENTS, "utf8") : "";
  if (!text.includes(TOKYO_HEADING)) {
    const header =
      `${TOKYO_HEADING}\n\n` +
      `ENSv2 on Ethereum Sepolia (chain 11155111), the 2026-09-15 deployment. Pools stay on Base Sepolia.\n` +
      `Contracts used (verified against docs.ens.domains/learn/deployments and cast code, 2026-09-26):\n` +
      ENS_SEPOLIA_ADDRESSES.map((a) => `- ${a.name}: \`${a.address}\``).join("\n") +
      `\n\nTransactions written by \`app/scripts/ens-bootstrap.ts\` (append-only):\n\n`;
    text = header + "---\n\n" + text;
  }
  const marker = "\n---\n";
  const at = text.indexOf(marker, text.indexOf(TOKYO_HEADING));
  text = at === -1 ? text + line + "\n" : text.slice(0, at) + line + "\n" + text.slice(at);
  writeFileSync(DEPLOYMENTS, text);
}

async function main(): Promise<void> {
  const parent = (process.env.ENS_PARENT_NAME?.trim() || "gohealthme.eth").toLowerCase();
  const label = firstLabel(parent);
  const ownerKey = envKey(["ENS_OWNER_PRIVATE_KEY", "PRIVATE_KEY"]);
  if (ownerKey === null) throw new Error("Set ENS_OWNER_PRIVATE_KEY (or PRIVATE_KEY in contracts/.env).");
  const owner = privateKeyToAccount(ownerKey);
  const agent = ensureAgentKey();
  const client = ensPublicClient();
  const wallet = ensWalletClient(owner);
  const state = loadState(parent);

  console.log(`ENSv2 bootstrap for ${parent} ${PLAN_ONLY ? "(plan only)" : ""}`);
  console.log(`  owner ${owner.address}`);
  console.log(`  agent ${agent.address}`);

  for (const c of ENS_SEPOLIA_ADDRESSES) {
    const code = await client.getCode({ address: c.address });
    if (code === undefined || code === "0x") throw new Error(`${c.name} ${c.address} has no bytecode on Sepolia`);
  }
  console.log(`  all ${ENS_SEPOLIA_ADDRESSES.length} ENSv2 addresses carry bytecode`);

  const gasPrice = await client.getGasPrice();
  let spentWei = 0n;
  const balance = () => client.getBalance({ address: owner.address });

  async function send(step: string, gasEstimate: bigint, fn: () => Promise<Hex>): Promise<TransactionReceipt> {
    const bal = await balance();
    const need = gasEstimate * gasPrice * 2n;
    if (bal - need < OWNER_FLOOR_ETH) {
      const short = OWNER_FLOOR_ETH + need - bal;
      throw new Error(
        `STOP before "${step}": owner holds ${formatEther(bal)} ETH, this step needs ~${formatEther(need)} and the floor is ${formatEther(OWNER_FLOOR_ETH)}. Faucet at least ${formatEther(short)} Sepolia ETH to ${owner.address}.`,
      );
    }
    const hash = await fn();
    const receipt = await client.waitForTransactionReceipt({ hash, timeout: 180_000 });
    if (receipt.status !== "success") throw new Error(`${step} reverted in ${hash}`);
    const cost = receipt.gasUsed * receipt.effectiveGasPrice;
    spentWei += cost;
    state.txs.push({ step, hash, gasEth: formatEther(cost) });
    saveState(state);
    recordDeployment(`- ${new Date().toISOString().slice(0, 10)} ${step}: [\`${hash}\`](${sepoliaTxUrl(hash)}) (gas ${receipt.gasUsed})`);
    console.log(`  done: ${step} ${hash} gas=${receipt.gasUsed}`);
    return receipt;
  }

  const plan: string[] = [];

  // ---- 1. proxies (skipped entirely when the parent already points at them)
  let registry = await client.readContract({ address: ENS_SEPOLIA.ethRegistry, abi: REGISTRY_ABI, functionName: "getSubregistry", args: [label] });
  let resolver = await client.readContract({ address: ENS_SEPOLIA.ethRegistry, abi: REGISTRY_ABI, functionName: "getResolver", args: [label] });
  const parentRegistered = registry !== ZERO && resolver !== ZERO;

  if (!parentRegistered) {
    const available = await client.readContract({ address: ENS_SEPOLIA.ethRegistrar, abi: ETH_REGISTRAR_ABI, functionName: "isAvailable", args: [label] });
    if (!available) throw new Error(`${parent} is not available and has no subregistry; it belongs to someone else`);

    // A proxy is a CREATE2 deploy keyed by (owner, salt): sending it twice
    // reverts. So before deploying, recover the proxy from a tx this state
    // already recorded for the step, and prove it with the factory itself.
    async function proxyFromLogs(logs: TransactionReceipt["logs"], impl: Address): Promise<Address | null> {
      const events = parseEventLogs({ abi: VERIFIABLE_FACTORY_ABI, logs, eventName: "ProxyDeployed" });
      const ev = events.find((e) => e.args.implementation.toLowerCase() === impl.toLowerCase());
      if (ev === undefined) return null;
      const verified = await client.readContract({ address: ENS_SEPOLIA.verifiableFactory, abi: VERIFIABLE_FACTORY_ABI, functionName: "verifyContract", args: [ev.args.proxyAddress] });
      if (verified.toLowerCase() !== impl.toLowerCase()) throw new Error(`proxy ${ev.args.proxyAddress} does not verify against ${impl}`);
      return ev.args.proxyAddress;
    }

    async function recoverProxy(step: string, impl: Address): Promise<Address | null> {
      for (const tx of state.txs.filter((t) => t.step === step)) {
        const receipt = await client.getTransactionReceipt({ hash: tx.hash });
        if (receipt.status !== "success") continue;
        const found = await proxyFromLogs(receipt.logs, impl);
        if (found !== null) return found;
      }
      return null;
    }

    async function deployProxy(step: string, impl: Address, salt: bigint, data: Hex): Promise<Address> {
      const recovered = await recoverProxy(step, impl);
      if (recovered !== null) {
        console.log(`  recovered ${step}: ${recovered} (from an earlier tx, verified by the factory)`);
        return recovered;
      }
      const receipt = await send(step, 400_000n, () =>
        wallet.writeContract({ account: owner, chain: null, address: ENS_SEPOLIA.verifiableFactory, abi: VERIFIABLE_FACTORY_ABI, functionName: "deployProxy", args: [impl, salt, data] }),
      );
      const proxy = await proxyFromLogs(receipt.logs, impl);
      if (proxy === null) throw new Error(`${step}: no ProxyDeployed event for ${impl} in ${receipt.transactionHash}`);
      return proxy;
    }

    if (state.registryProxy === undefined) {
      plan.push("deploy UserRegistry proxy");
      if (!PLAN_ONLY) {
        state.registryProxy = await deployProxy(
          "deploy UserRegistry proxy (VerifiableFactory)",
          ENS_SEPOLIA.userRegistryImpl,
          BigInt(keccak256(stringToBytes(`${parent}:registry:v1`))),
          encodeFunctionData({ abi: REGISTRY_ABI, functionName: "initialize", args: [[{ account: owner.address, roleBitmap: ALL_ROLES }]] }),
        );
        saveState(state);
        recordDeployment(`  - UserRegistry proxy: \`${state.registryProxy}\``);
      }
    }
    if (state.resolverProxy === undefined) {
      plan.push("deploy PermissionedResolver proxy");
      if (!PLAN_ONLY) {
        state.resolverProxy = await deployProxy(
          "deploy PermissionedResolver proxy (VerifiableFactory)",
          ENS_SEPOLIA.permissionedResolverImpl,
          BigInt(keccak256(stringToBytes(`${parent}:resolver:v1`))),
          encodeFunctionData({ abi: PERMISSIONED_RESOLVER_ABI, functionName: "initialize", args: [[{ account: owner.address, roleBitmap: ALL_ROLES }], []] }),
        );
        saveState(state);
        recordDeployment(`  - PermissionedResolver proxy: \`${state.resolverProxy}\``);
      }
    }

    // ---- 2. register the parent
    const reg = state.registryProxy ?? ZERO;
    const res = state.resolverProxy ?? ZERO;
    const [base, premium] = await client.readContract({ address: ENS_SEPOLIA.ethRegistrar, abi: ETH_REGISTRAR_ABI, functionName: "getRegisterPrice", args: [label, REGISTRATION_SECONDS, ENS_SEPOLIA.mockUsdc] });
    const price = base + premium;
    plan.push(`register ${parent} for 1 year (${price} MockUSDC base units)`);
    if (!PLAN_ONLY) {
      const usdcBal = await client.readContract({ address: ENS_SEPOLIA.mockUsdc, abi: MOCK_USDC_ABI, functionName: "balanceOf", args: [owner.address] });
      if (usdcBal < price) {
        await send("mint MockUSDC for the registration fee", 90_000n, () =>
          wallet.writeContract({ account: owner, chain: null, address: ENS_SEPOLIA.mockUsdc, abi: MOCK_USDC_ABI, functionName: "mint", args: [owner.address, price * 2n] }),
        );
      }
      const allowance = await client.readContract({ address: ENS_SEPOLIA.mockUsdc, abi: MOCK_USDC_ABI, functionName: "allowance", args: [owner.address, ENS_SEPOLIA.ethRegistrar] });
      if (allowance < price) {
        await send("approve ETHRegistrar for MockUSDC", 60_000n, () =>
          wallet.writeContract({ account: owner, chain: null, address: ENS_SEPOLIA.mockUsdc, abi: MOCK_USDC_ABI, functionName: "approve", args: [ENS_SEPOLIA.ethRegistrar, price * 2n] }),
        );
      }
      if (state.secret === undefined) {
        state.secret = toHex(crypto.getRandomValues(new Uint8Array(32)));
        saveState(state);
      }
      const secret = state.secret;
      const zeroRef = `0x${"00".repeat(32)}` as Hex;
      const commitment = await client.readContract({ address: ENS_SEPOLIA.ethRegistrar, abi: ETH_REGISTRAR_ABI, functionName: "makeCommitment", args: [label, owner.address, secret, reg, res, REGISTRATION_SECONDS, zeroRef] });
      const minAge = await client.readContract({ address: ENS_SEPOLIA.ethRegistrar, abi: ETH_REGISTRAR_ABI, functionName: "MIN_COMMITMENT_AGE" });
      let committedAt = await client.readContract({ address: ENS_SEPOLIA.ethRegistrar, abi: ETH_REGISTRAR_ABI, functionName: "commitmentAt", args: [commitment] });
      if (committedAt === 0n) {
        const r = await send(`commit ${parent}`, 60_000n, () =>
          wallet.writeContract({ account: owner, chain: null, address: ENS_SEPOLIA.ethRegistrar, abi: ETH_REGISTRAR_ABI, functionName: "commit", args: [commitment] }),
        );
        committedAt = (await client.getBlock({ blockNumber: r.blockNumber })).timestamp;
      }
      for (;;) {
        const now = (await client.getBlock()).timestamp;
        if (now >= committedAt + minAge + 2n) break;
        const waitS = Number(committedAt + minAge + 3n - now);
        console.log(`  waiting ${waitS}s for the commitment to age`);
        await new Promise((r) => setTimeout(r, waitS * 1000));
      }
      await send(`register ${parent} (ETHRegistrar, subregistry + resolver set)`, 450_000n, () =>
        wallet.writeContract({ account: owner, chain: null, address: ENS_SEPOLIA.ethRegistrar, abi: ETH_REGISTRAR_ABI, functionName: "register", args: [label, owner.address, secret, reg, res, REGISTRATION_SECONDS, ENS_SEPOLIA.mockUsdc, zeroRef] }),
      );
      registry = reg;
      resolver = res;
    }
  } else {
    console.log(`  ${parent} registered: registry ${registry}, resolver ${resolver}`);
  }

  if (PLAN_ONLY && !parentRegistered) {
    plan.push("register spotter subname", "set spotter address records", `grant ${RECEIPT_KEY_LIST.length} receipt keys`, "fund agent");
    return finish(plan);
  }

  // ---- 3. spotter subname, owned by the agent with no registry roles
  const agentLabelOwner = await client.readContract({ address: registry, abi: REGISTRY_ABI, functionName: "findOwner", args: [AGENT_LABEL] });
  if (agentLabelOwner === ZERO) {
    plan.push(`register ${agentName(parent)} to the agent with roleBitmap 0`);
    if (!PLAN_ONLY) {
      await send(`register ${agentName(parent)} to the agent, roleBitmap ${AGENT_NAME_ROLES}`, 250_000n, () =>
        wallet.writeContract({ account: owner, chain: null, address: registry, abi: REGISTRY_ABI, functionName: "register", args: [AGENT_LABEL, agent.address, ZERO, resolver, AGENT_NAME_ROLES, NO_EXPIRY] }),
      );
    }
  } else if (agentLabelOwner.toLowerCase() !== agent.address.toLowerCase()) {
    console.warn(`  WARNING ${agentName(parent)} is owned by ${agentLabelOwner}, not the configured agent ${agent.address}`);
  }

  // ---- 4. spotter address records
  const pools = (process.env.HEALTH_POOLS_ADDRESS || process.env.NEXT_PUBLIC_HEALTH_POOLS_ADDRESS || "").trim() as Address;
  let settler: Address | null = null;
  if (/^0x[0-9a-fA-F]{40}$/.test(pools)) {
    const base = createPublicClient({ chain: baseSepolia, transport: http(process.env.BASE_SEPOLIA_RPC_URL || "https://sepolia.base.org") });
    settler = await base.readContract({ address: pools, abi: parseAbi(["function authorizedSettler() view returns (address)"]), functionName: "authorizedSettler" });
    console.log(`  Base Sepolia settler (read from HealthPoolsV3 ${pools}): ${settler}`);
  }
  const name = agentName(parent);
  const readAddr = async (coin: bigint): Promise<string> => {
    const r = await client.getEnsAddress({ name, coinType: coin === ETH_COIN_TYPE ? undefined : coin, universalResolverAddress: ENS_SEPOLIA.universalResolver }).catch(() => null);
    return (r ?? "").toLowerCase();
  };
  const calls: Hex[] = [];
  if ((await readAddr(ETH_COIN_TYPE)) !== agent.address.toLowerCase()) calls.push(setAddressCalldata(name, ETH_COIN_TYPE, agent.address));
  if (settler !== null && (await readAddr(BASE_SEPOLIA_COIN_TYPE)) !== settler.toLowerCase()) calls.push(setAddressCalldata(name, BASE_SEPOLIA_COIN_TYPE, settler));
  if (calls.length > 0) {
    plan.push(`set ${calls.length} address record(s) on ${name}`);
    if (!PLAN_ONLY) {
      await send(`set ${name} addr(60) = agent, addr(84532) = Base settler`, 200_000n, () =>
        wallet.writeContract({ account: owner, chain: null, address: resolver, abi: PERMISSIONED_RESOLVER_ABI, functionName: "multicall", args: [calls] }),
      );
    }
  }

  // ---- 5. per-key delegation (Enhanced Access Control on the resolver)
  const grants: Hex[] = [];
  for (const key of RECEIPT_KEY_LIST) {
    const has = await client.readContract({ address: resolver, abi: PERMISSIONED_RESOLVER_ABI, functionName: "hasRoles", args: [textResource(key), RESOLVER_ROLE_SET_TEXT, agent.address] });
    if (!has) grants.push(encodeFunctionData({ abi: PERMISSIONED_RESOLVER_ABI, functionName: "grantSetterRoles", args: [textSetterGrant(parent, key), agent.address] }));
  }
  if (grants.length > 0) {
    plan.push(`grant ROLE_SET_TEXT on ${grants.length} receipt key(s) to the agent`);
    if (!PLAN_ONLY) {
      await send(`grant the agent ROLE_SET_TEXT on ${grants.length} receipt keys (grantSetterRoles)`, 120_000n * BigInt(grants.length), () =>
        wallet.writeContract({ account: owner, chain: null, address: resolver, abi: PERMISSIONED_RESOLVER_ABI, functionName: "multicall", args: [grants] }),
      );
    }
  }

  // ---- 6. gas for the agent's receipt writes
  const agentBal = await client.getBalance({ address: agent.address });
  if (agentBal < AGENT_MIN_ETH) {
    plan.push(`send ${formatEther(AGENT_TOPUP_ETH)} Sepolia ETH to the agent`);
    if (!PLAN_ONLY) {
      await send(`fund the agent with ${formatEther(AGENT_TOPUP_ETH)} Sepolia ETH`, 21_000n, () =>
        wallet.sendTransaction({ account: owner, chain: null, to: agent.address, value: AGENT_TOPUP_ETH }),
      );
    }
  }

  console.log(`  spent this run: ${formatEther(spentWei)} ETH; owner now ${formatEther(await balance())} ETH`);
  finish(plan);
}

function finish(plan: string[]): void {
  if (PLAN_ONLY) {
    console.log(plan.length === 0 ? "Nothing left to do." : `Left to do:\n  - ${plan.join("\n  - ")}`);
  } else {
    console.log("Bootstrap complete.");
  }
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
